### ISSUE TITLE
Abort connect attempt and return to list

### ISSUE THREAD

**Issue by leorolland** [charmbracelet/wishlist#108]
Hi,
Thanks for all your work on this repository and other CLIs you worked on ;)

I feel frustrated not to have any way to abort/cancel a pending connect attempt.

When a server is unreachable, we have to wait 30 seconds for a timeout, a shortcut like Control + C or Q would be useful !

**Comment by caarlos0** [comment]
Ok, both #109 and #110 should help:

- #109: cancels connection on ctrl+c (local mode only)
- #110: allow to customize the connection timeout

**Comment by caarlos0** [comment]
closing, as I think this covers what we can cover right now
