### ISSUE TITLE
brew install sha256 mismatch

### ISSUE THREAD

**Issue by jheroy** [charmbracelet/wishlist#118]
Error: wishlist: SHA256 mismatch
Expected: e26cf9ed70c97db4aba9d4c08b48bc10f616592b8d7ca61fd3401818fcecc61b
  Actual: 375a2e52ed7a94b2853f3da7bfcf53e90536fbff3c944404f174efc66aecdc8f

**Comment by aymanbagabas** [comment]
Thank you for reporting! This is now fixed in https://github.com/charmbracelet/homebrew-tap/commit/e45cfe5cdde95fbefbc38b7f87b366fdd688d13e
