### ISSUE TITLE
tbd: improve error messages

### ISSUE THREAD

**Issue by bashbunni** [charmbracelet/wishlist#130]
Would be cool to show potential solutions for users when an error occurs. e.g. if a port is misconfigured, give them the option to edit their config.yaml and reload wishlist on save. When there is no ForwardAgent installed, give suggestions based on operating system on how to install an agent? Thoughts?

**Comment by caarlos0** [comment]
hmm its hard to know if the port is missconfigured... it might be just down because the target service is down.

about ssh agents: it might be the default openssh agent, or any other (there are many)... so I don't know how much that would help 🤔

**Comment by caarlos0** [comment]
closing as I don't think this is still relevant, plz reopen otherwise 🙏🏻
