### ISSUE TITLE
Concept of a tunnel?

### ISSUE THREAD

**Issue by vsoch** [charmbracelet/wishlist#145]
Hi! I'm new to the set of tools here, and I'm pretty excited to try them out! I was wondering how this might relate to a tunnel - e.g., would it be that if I have  a wish app locally, I could connect to a server (with other apps) and continue as many levels as needed until I find what I need? What about something like a proxy jump (so I could see nested apps from two levels up, for example). Thanks!

**Comment by caarlos0** [comment]
Hey,

Not 100% sure I understood your question, but if I did: yes, you can SSH from one Wishlist instance to another, indefinitely (in theory, haven't tested more than 3 🤔).

`ProxyJump` is not supported though.

**Comment by vsoch** [comment]
To give more context, the use case I'm interested in is high performance computing, where it's common to want to interact with a compute note via a login node from your local machine. E.g.,:

```
<local machine> -> <login node> <compute node>
```
and the compute node is isolated, meaning no ports can be opened and we typically have to use an [ssh tunnel](https://www.concordia.ca/ginacody/aits/support/faq/ssh-tunnel.html) through the login node back to our host.  These tunnels can actually be done with ports or unix sockets!

So let's say I have an app (developed with this library maybe) running on the compute node - first  can I assume anything that is written in Go / able to be interacted with from Go is contender to be included in a wish app? and if so, could I theoretically interact with it from my local machine via wish? :thinking:

**Comment by caarlos0** [comment]
SSH port forward via wishlist is not supported, if thats the question. 
Wishlist can SSH into any valid SSH host, it can be a wish app, another shell, pretty much anything really.

I'm still not sure if that's what you were asking though, sorry if its not.

**Comment by vsoch** [comment]
It's ok, thank you for your help! I'm trying to figure out ways to make the chronically (kind of bad) experience of interacting with HPC resources slightly less so. It sounds like I couldn't easily do some of the harder stuff like tunneling, and I'm happy to close the issue.
