### ISSUE TITLE
ssh: setenv failed when connecting

### ISSUE THREAD

**Issue by LennyPenny** [charmbracelet/wishlist#151]
Version: 0.9.0

`~/.ssh.config`: 
```
Host myhost
  User lenny
  HostName 10.x.x.x
```

```
Wishlist

Something went wrong:

ssh: setenv failed
```

When I just run `ssh myhost` it works just fine.

I'm also using gpg-agent if that could be affecting this. 

Wishlist.log: 
```
2023/02/09 21:51:05 setting delegate height: 2
2023/02/09 21:51:06 offering public key via ssh agent: ssh-ed25519 xxx
2023/02/09 21:51:06 offering public key via ssh agent: ssh-ed25519 xxx
2023/02/09 21:51:06 ignored env PWD
2023/02/09 21:51:06 ignored env DISPLAY
...
2023/02/09 21:51:06 failed to close: read tcp 10.42.32.1:47058->10.42.33.5:22: use of closed network connection
2023/02/09 21:51:06 got an error: failed to create session: could not set env: [<huge list of env vars] ssh: setenv failed
```

**Comment by caarlos0** [comment]
Hey @LennyPenny , thanks for reporting this... could you try with `main`? I improved the error message so we know which env is failing to set... that might help debug it 🙏

**Comment by LennyPenny** [comment]
```
2023/02/10 15:48:39 got an error: failed to create session: could not set env: LC_CTYPE=de_DE.UTF-8: ssh: setenv failed
2023/02/10 15:48:39 error: failed to create session: could not set env: LC_CTYPE=de_DE.UTF-8: ssh: setenv failed
```

maybe this issue is that de_DE.UTF-8 is not installed on the server

**Comment by LennyPenny** [comment]
Just checked and it is in fact installed!

**Comment by caarlos0** [comment]
@LennyPenny sorry for the delay, missed your response here.

If you send those envs to SSH using plain `ssh`, does it work? I think its probably warning you about it, and maybe we need to do the same instead of hard-erroring...

Could you try? Thanks!

**Comment by LennyPenny** [comment]
aah hmm, like I'm not sure it should even setenv all these vars? Like I don't think it makes sense to set PWD on the remote or DESKTOP_SESSION on a server I'm sshing into

**Comment by caarlos0** [comment]
It should be setting only lang and lc_* flags unless you specified the others somewhere. 🤔

**Comment by caarlos0** [comment]
since dfc7c3d it won't fail if setenv errors... so this should be fixed...

can you give the `main` branch a try @LennyPenny ?

**Comment by LennyPenny** [comment]
works like a charm now!
