### ISSUE TITLE
Set logfile default location to local application state folder

### ISSUE THREAD

**Issue by vinicius507** [charmbracelet/wishlist#161]
Currently wishlist places the `wishlist.log` file in the current folder, which ends up cluttering the users filesystem.

It would be best if we could specify the directory in which the logfile is placed using the `.yaml` config file, while defaulting to OS default local application data folder (e.g. `XDG_STATE_HOME` in Linux, `%LOCALAPPDATA%` in Windows).

An alternative to using the config file for this setting would be to use an environment variable such as `WISHLIST_LOG_DIR` to override the default directory.

**Comment by caarlos0** [comment]
check #165

**Comment by vinicius507** [comment]
> check #165

Thanks a ton!
