### ISSUE TITLE
No such host when trying to connect

### ISSUE THREAD

**Issue by lnfel** [charmbracelet/wishlist#207]
Using MacOS (intel) and just trying out wishlist for the first time (locally). Downloaded the binary from [release page](https://github.com/charmbracelet/wishlist/releases/tag/v0.13.0).

Started wishlist on installation directory:
```sh
./wishlist
```

Showed all my available ssh connections, one of them being:
> deploy-dev
> ssh://deploy-dev:22

Tried connecting to it by providing the password, but errors out with:
> Something went wrong:
> lookup deploy-dev: no such host

My `.ssh/config` is this:
```sh
Host deploy-dev
Hostname ec2-gotta-guess-it.compute.amazonaws.com
User someone
ForwardX11 yes
IdentityFile ~/path/to/id_rsa
ServerAliveInterval 50
```

I think it should connect using the `Hostname` no?

**Comment by caarlos0** [comment]
found it, btw, its trying to match specifically `HostName` (and not `Hostname`). Its fixed in main, but if you don't want to compile from source in the meantime, you can change your config to `HostName` (Name capitalized)

Thanks for reporting this 😄
