### ISSUE TITLE
scoop install fails

### ISSUE THREAD

**Issue by dezren39** [charmbracelet/wishlist#235]
PS C:\Users\drewr\scoop-charmbracelet> scoop install wishlist
Couldn't find manifest for 'wishlist'.
![image](https://github.com/charmbracelet/wishlist/assets/11225574/42c3c751-4324-4d9c-9276-edc694884666)

**Comment by caarlos0** [comment]
sorry about that!

instruction are incomplete in the readme, you'll need to add our bucket first: 


```sh
scoop bucket add charm https://github.com/charmbracelet/scoop-bucket
scoop install wishlist
```
