### ISSUE TITLE
Add support for the Include directive in the SSH config file

### ISSUE THREAD

**Issue by curio77** [charmbracelet/wishlist#262]
wishlist should support the `Include` directive in the SSH config file, used to incorporate separately-held SSH configurations (typically, host definitions).  Otherwise, hosts defined this way won't be considered and listed in wishlist.

**Comment by curio77** [comment]
Huh?  Doesn't work for me. 🤔

Just checked again, nope, neither with full (relative) paths nor with wildcards (e.g., `Include config.d/*`).  This is with the latest version of wishlist installed via `go install github.com/charmbracelet/wishlist/cmd/wishlist@latest`.

**Comment by caarlos0** [comment]
what does the logs say?

can you provide a minimal reproducible example? 

I just checked here: it is working, and there are tests enforcing it works. So, if it isn't for you, probably there's something different in your configs...

**Comment by curio77** [comment]
Alright…

Trying to do this, I think I've identified the issue.  `ssh` take the `Include` directive as relative to the location of the file, i.e., relative paths in `~/.ssh/config` are resolved relative to `~/.ssh`.  wishlist, OTOH, resolves relative to the CWD, hence it works when I run it from the `~/.ssh` directory but not otherwise.  This explains the observed and reported behavior, and I think that's a bug.

**Comment by curio77** [comment]
Addendum: And even so, wildcards don't work, it only works with names but not with something like `config.d/*` even if I run wishlist from `~/.ssh`.

**Comment by caarlos0** [comment]
can you check #263?
