### ISSUE TITLE
Support wildcards in `Include`

### ISSUE THREAD

**Issue by jvrst** [charmbracelet/wishlist#314]
**Is your feature request related to a problem? Please describe.**
I use `Include ~/.ssh/config.d/*.config` at the top of my `~/.ssh/config`, pointing to about 5 different configs (e.g. one for a specific customer, one for my homelab etc). It seems that wishlist doesn't resolve these. 

**Describe the solution you'd like**
I'd like to see the hosts in those configs available when I run `wishlist`

**Describe alternatives you've considered**
I could rewrite my whole ssh config back to a single file, which is an option, but then I'd lose some important structuring. I could also hardcode each config into a separate Include, which is probably what I'll end up doing for now.

I'll check out and see if I can do this myself, but any pointers are welcome :)

**Comment by caarlos0** [comment]
already supported on main

#263

**Comment by jvrst** [comment]
Thanks @caarlos0! didn't see it in the readme. Will update to main, seems the default brew version is a bit behind :)

**Comment by caarlos0** [comment]
yeah, I think I'm gonna make a new release soon
