### ISSUE TITLE
Installation method support?

### ISSUE THREAD

**Issue by ryuheechul** [charmbracelet/wishlist#32]
It would be great to be able to install this via [Homebrew](https://brew.sh/)/[Nix](https://search.nixos.org/packages).
Like [glow on nix](https://search.nixos.org/packages?channel=unstable&from=0&size=50&sort=relevance&type=packages&query=glow) and [glow on brew](https://formulae.brew.sh/formula/glow#default).

**Comment by caarlos0** [comment]
hey, thanks for the issue @ryuheechul , I'll look into it

meanwhile, you can install it with our homebrew tap: 

```sh
brew install charmbracelet/tap/wishlist
```

**Comment by caarlos0** [comment]
well, docs should be updated, so, closing this, thanks!
