### ISSUE TITLE
Add function to update the endpoints during runtime

### ISSUE THREAD

**Issue by jon4hz** [charmbracelet/wishlist#40]
Wishlist as a library is super awesome since it allows you to dynamically generate the wishlist endpoints e.g. from a dcim tool.
However, you can only generate the endpoints at the initial startup and every time you want to update the endpoints, you have to restart the whole service. 
What do you think about adding a function, that allows to update the endpoints at runtime without any downtime?

**Comment by WIZARDISHUNGRY** [comment]
This would be useful if you wanted to include endpoints from some kind of service discovery (mDNS).

**Comment by caarlos0** [comment]
hey, would #51 work for your cases?

**Comment by jon4hz** [comment]
Hey, at first glance, it looks like exactly what I'm looking for. Thanks a lot! 
Just one question. How does this behave when a user is currently in wishlist tui and the endpoints change in the background? Is the view updated automatically or do the new endpoints only show up on a reconnect?

**Comment by caarlos0** [comment]
since its a command, I believe it'll refresh live...
