### ISSUE TITLE
Error: invalid node on app "x": "#Hostname"

### ISSUE THREAD

**Issue by robertandrewblackburn** [charmbracelet/wishlist#46]
Wishlist crashes on startup on my ssh config with the line:

`#Hostname`

Adding a space between the `#` and `Hostname` resolves it, as does adding anything after `Hostname`, so seems like something's going on with comment parsing still.

Pulling down the repo to have a look myself, but I've never touched Go (seems like a good first issue?) so logging this here just in case I give up.

**Comment by caarlos0** [comment]
Hey, this should have been fixed in https://github.com/charmbracelet/wishlist/commit/dc487854140e6838003a6e568b897e988947f85a, which is not released yet…

will do it asap 🙏

**Comment by caarlos0** [comment]
hey, can you try on v0.3.0?

**Comment by robertandrewblackburn** [comment]
Hah, I saw that commit and thought it had already been merged. v0.3.0 indeed fixes the crash.
Thanks!
