### ISSUE TITLE
Usage with non-interactive programs such as scp

### ISSUE THREAD

**Issue by shadowrylander** [charmbracelet/wishlist#47]
Hello!

As in the title; how would I use this with something like `scp`? Would I have to chain hosts or proxyjump, for example?

Thank you kindly for the information!

**Comment by caarlos0** [comment]
Hey!

Right now I'm afraid its not possible... but I'm curious...  what your use cases are and how do you imagine it should work?

**Comment by caarlos0** [comment]
hmmm.. it needs to be in an interactive terminal unfortunately

you might be able to run it with something like `ssh host list-item-name` if the target itself is not interactive 

wishlist does not understand port-forwarding and more complex options yet, something to keep in mind.
available options are just the ones here for now: https://github.com/charmbracelet/wishlist/blob/e75812917d69741209d119c64c171edb87e0000c/sshconfig/parse.go#L60-L69

**Comment by shadowrylander** [comment]
Actually, that work too; is there a way to get the address and port of a `wishlist` target, so that I can just do something like `ssh -p $(wishlist --get port target) $(wishlist --get address target)`?

**Comment by caarlos0** [comment]
maybe at that point it is simpler to set it up in your `~/.ssh/config` so you can just `ssh target`?

**Comment by shadowrylander** [comment]
Well then I'd need multiple entries, for `wishlist` and `~/.ssh/config`, wouldn't I? I thought it may be easier to have them all in one place.

**Comment by caarlos0** [comment]
wishlist can also read ssh config files, so you could have a single file.

There are some example links in the readme, in case that's helpful: https://github.com/charmbracelet/wishlist#running-it

**Comment by shadowrylander** [comment]
Oh! Well my apologies, then; I had forgotten about that bit! Thanks! Although, does this mean `wishlist` follows `ssh's` own proxyjumps? Sorry, a little confused there.

**Comment by shadowrylander** [comment]
Oh, those are `~/.ssh/config` options; my bad. Ah, well... Thanks for all the help, as it were! I'll go ahead and close this, then!
