### ISSUE TITLE
Handshake failed error

### ISSUE THREAD

**Issue by BLucky-gh** [charmbracelet/wishlist#60]
When trying to connect to any server I'm receiving an error:
`something went wrong:failed to create session: connection failed: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain`

I'm running wishlist in local tui mode, the `config` file is as follows (edited for privacy)

```
IdentityFile 	~/.ssh/id_rsa

Host		github.com
  AddKeysToAgent yes
  IdentityFile	~/.ssh/id_ed25519

Host 		*.mydomain.tld
  IdentityFile 	~/.ssh/id_rsa

Host 		foo
  HostName	x.x.x.x
  User		bar
  Port		222

Host 		baz
  HostName	y.y.y.y
  User		root
  Port		1774
```

Note: the public keys are confirmed to work normally, issues only arise when connecting through wishlist

**Comment by caarlos0** [comment]
anything else in the `wishlist.log` file?

**Comment by BLucky-gh** [comment]
2) all of them

1) where are the logs located?

**Comment by caarlos0** [comment]
> 1 ) where are the logs located?

should be in the folder in which you executed wishlist

**Comment by caarlos0** [comment]
> 2 ) all of them

my guess is that its the same thing that happens here: https://github.com/charmbracelet/soft-serve/issues/48#issuecomment-1018473734

**Comment by BLucky-gh** [comment]
here's the logs 

```2022/04/20 22:34:50 using SSH agent
2022/04/20 22:34:50 using "/Users/blucky/.ssh/id_rsa"
2022/04/20 22:34:50 using "/Users/blucky/.ssh/id_ed25519"
2022/04/20 22:34:50 got an error: failed to create session: connection failed: ssh: handshake failed: possible man-in-the-middle attack: knownhosts: key mismatch
2022/04/20 22:34:57 using SSH agent
2022/04/20 22:34:57 using "/Users/blucky/.ssh/id_rsa"
2022/04/20 22:34:57 got an error: failed to create session: connection failed: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
2022/04/20 22:35:06 using SSH agent
2022/04/20 22:35:06 using "/Users/blucky/.ssh/id_rsa"
2022/04/20 22:35:13 got an error: failed to create session: connection failed: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
2022/04/20 22:35:32 using SSH agent
2022/04/20 22:35:32 using "/Users/blucky/.ssh/id_rsa"
2022/04/20 22:35:35 got an error: failed to create session: connection failed: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
2022/04/20 22:47:13 using SSH agent
2022/04/20 22:47:13 using "/Users/blucky/.ssh/id_rsa"
2022/04/20 22:47:13 got an error: failed to create session: connection failed: ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain```

by the way the mitm/key mismatch error is not wishlist's fault I think, since I do occasionally get that error with regular ssh connecting to that host (which is github)

**Comment by BLucky-gh** [comment]
> > 2 ) all of them
> 
> my guess is that its the same thing that happens here: [charmbracelet/soft-serve#48 (comment)](https://github.com/charmbracelet/soft-serve/issues/48#issuecomment-1018473734)

is that the one where the go library that charm uses can't handle rsa keys?

**Comment by BLucky-gh** [comment]
> ah, I think I get it.. you have a SSH agent running, but it doesnt have a key that's accepted...

Not sure what you mean, running `ssh-add -L` shows that the key in question is indeed in the agent

**Comment by caarlos0** [comment]
#62 adds more logs
