### ISSUE TITLE
Reconnect to wishlist sometimes fails

### ISSUE THREAD

**Issue by jon4hz** [charmbracelet/wishlist#72]
Hey!
I've been using wishlist (in server mode) a lot lately. Overall it works great but from time to time it fails to take me back to the list after closing a remote ssh connection. 
A few times wishlist just tried to reconnect to the same server, when I then close that connection a second time, wishlist throws an error `something went wrong:session failed: Process exited with status 127`. 
Unfortunately I couldn't figure out how to reproduce the error consistently.

**Comment by caarlos0** [comment]
Let's keep an eye on it, I could not reproduce it here, if anyone finds a way to repro this, lmk please.

Also, if you also get this err, feel free to ping here! 

Cheers and thanks for the report @jon4hz 🙏
