### ISSUE TITLE
Enhancement: look for config.yml in $HOME/.ssh

### ISSUE THREAD

**Issue by Cordelya** [charmbracelet/wishlist#73]
Case:
- I initiate ssh connections to other machines from a variety of working directories.
- My `$HOME/.ssh/config` file contains a mix of regular SSH connections and git repositories, which are only used by git
- In order to consistently use a default config.yml (and therefore have a connection list that excludes git repositories), I need to always pass wishlist the path to my config.yml

Suggestion: Add `$HOME/.ssh/config.[yml|yaml]` or perhaps `$HOME/.ssh/wishlist/config.[yml|yaml]` to the list of places wishlist automatically looks for configs, ahead of `$HOME/.ssh/config` and `/etc/ssh/ssh_config`.

**Comment by muesli** [comment]
I don't think it's a good idea to start polluting config paths of other software. If you really have to, you can store it there and symlink to it.

**Comment by Cordelya** [comment]
The change in 74 works for me. Putting in $HOME/.ssh was just a suggestion. I was mainly looking for a static config location that gets checked before $HOME/.ssh/config.

Thank you!
